source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'webrick', '~> 1.9'

group :jekyll_plugins do
  gem 'jekyll-seo-tag', '~> 2.8'
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jekyll-toc', '~> 0.19'
end
